# Generated by Django 6.1 on 2026-09-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installeddevice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='devices/'),
        ),
    ]
